config/routes.rb
KnOverFlow::Application.routes.draw do
  resources :questions do
    resources :votes, only: [:create]
    resources :comments, only: [:new, :create]
    resources :answers, only: [:new, :create, :edit, :update, :destroy] 
  end

  resources :answers, only: [:edit, :update, :destroy] do
  	resources :comments, only: [:new, :create]
    resources :votes, only: [:create]
  end

  resources :comments, only: [:edit, :update, :destroy]

  root to: 'questions#index'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable

  attr_accessible :title, :content

  validates :title, :content, :user, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  def index
    @questions = Question.all
  end

  def new
    if logged_in?
      @question = Question.new
    else
      flash[:error] = "You must be signed in to ask a question."
      redirect_to new_session_path 
    end
  end
  
  def create # need error messaging / validations on model
    @question = Question.new(params[:question])
    @question.user = current_user
    if @question.save
      redirect_to question_path(@question)
    else
      flash[:error] = "Error!"
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.user == current_user
      if @question.comments
        @question.comments.destroy_all
      end
      if @question.answers
        @question.answers.destroy_all
      end
      @question.destroy
      redirect_to root_path
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update 
    @question = Question.find(params[:id])
    @question.title = params["question"]["title"]
    @question.content = params["question"]["content"]
    if @question.save
      redirect_to question_path(@question)
    else
      redirect_to edit_question_path(@question)
      flash[:error] = "Error!"
    end
  end
end

app/views/questions/edit.html.erb
<h1>Edit Your Question Here!</h1>
  <%= flash[:error] if flash[:error] %>
  <%= form_for @question do |f| %>
    
  <%= f.label :title %>
  <%= f.text_field :title %>
 
  <%= f.label :content %>
  <%= f.text_area :content %>
 
  <%= f.submit %>
<% end %>

app/views/questions/index.html.erb
<h1>Welcome to KnOverflow</h1>

<h3><%= link_to "ask a question", new_question_path %></h3>

<% unless @questions.empty? %>
  <h3>these are all the questions</h3>
  <br />
  <ul>
   <% @questions.each do |question| %>
   <li><%= link_to question.title, question_path(question) %></a>&nbsp;<% if question.user == current_user %><%= button_to "delete", question_path(question), {method: :delete} %><%= button_to "edit", edit_question_path(question), {method: :get} %><% end %></li>
   <% end %>  
 </ul>
<% end %>

app/views/questions/new.html.erb
<h1>Post a Question Here!</h1>
<% if current_user %>
  <%= flash[:error] if flash[:error] %>
  <%= form_for @question do |f| %>
    
    <%= f.label :title %>
    <%= f.text_field :title %>
   
    <%= f.label :content %>
    <%= f.text_area :content %>
   
    <%= f.submit %>
  <% end %>
<% end %>

app/views/questions/show.html.erb
<div id='question_display' class="absolute-show" >
  <div class='questions'>
  <span><% if @question.user == current_user %><%= button_to "delete", question_path(@question), {method: :delete} %><%= button_to "edit", edit_question_path(@question.id), {method: :get} %><% end %></span>
    <h1><%= @question.title %></h1>
    <h3><%= @question.content %></h3>
    <%= render partial: '/comments/comments', locals: {commentable: @question } %>
  <br/>
   <div class='create_comment'>
    <span class='click_new_comment'><%= link_to 'create comment', new_question_comment_path(@question), remote: true %></span>
  </div>
  <br/>
   <div id='click_new_answer'><%= link_to 'answer question', new_question_answer_path(@question), remote: true %>
    <span id='create_answer'></span>
  </div>
  </div>
  <div class="answers">
    <% if @question.answers.any? %>
    <h4><%= @question.answers.count %> answers below:</h4>
        <% @question.answers.all.each do |answer| %>
      <%= render partial: 'answers/answer', locals: {answer: answer} %>
      <% end %>
    <% end %>
    <br/>
  </div>
</div>