config/routes.rb
KnOverFlow::Application.routes.draw do
  resources :questions do
    resources :votes, only: [:create]
    resources :comments, only: [:new, :create]
    resources :answers, only: [:new, :create, :edit, :update, :destroy] 
  end

  resources :answers, only: [:edit, :update, :destroy] do
  	resources :comments, only: [:new, :create]
    resources :votes, only: [:create]
  end

  resources :comments, only: [:edit, :update, :destroy]

  root to: 'questions#index'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable

  attr_accessible :content

  validates :content, :question, :user, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def index
  end

  def new
    question = Question.find(params[:question_id])
    render json: {
      html: render_to_string(partial: 'form', locals: { question: question, answer: question.answers.build })
    }
  end

  def create
    answer = Answer.new(params[:answer])
    answer.user_id = current_user.id
    answer.question_id = params[:question_id]
    if answer.save
      render json: {
        html: render_to_string(partial: 'answer', locals: { answer: answer })
      }
    else
      question = Question.find(answer.question_id)
      render json: {
        html: render_to_string(partial: 'form', locals: { question: question, answer: answer })
      }, status: :unprocessable_entity
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @question = Question.find(@answer.question_id)
    if @answer.user == current_user
      if @answer.comments
        @answer.comments.destroy_all
      end
      @answer.destroy
      redirect_to question_path(@question)
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    @question = Question.find(@answer.question_id)
    @answer.content = params["answer"]["content"]
    if @answer.save
      redirect_to question_path(@question)
    else
      redirect_to edit_answer_path(@answer)
      flash[:error] = "Error!"
    end
  end
end

app/views/answers/_answer.html.erb
<div class='answer_display'>
  <li id='<%=dom_id(answer)%>'><h5><%= answer.content %></h5></li>
  <%= render partial: '/comments/comments', locals: {commentable: answer } %>
  <br />
  <div class='create_comment'>
    <span class='click_new_comment'><%= link_to 'create comment', new_answer_comment_path(answer), remote: true %></span> 
  </div> 
   <div class='votes'>
     <%= link_to "Upvote", answer_votes_path(answer, up_voted: true), method: :post, remote:true, class: 'up_vote' %>
      <%= link_to "Downvote", answer_votes_path(answer), method: :post, remote:true, class: 'up_vote' %>
   </div>
  <br />
</div>

app/views/answers/_form.html.erb
<h4>Post an Answer Here!</h4>
<%= form_for [question, answer],remote: true do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, placeholder: "answer content" %>
  <%= f.submit %>
  <% if answer.errors[:content] %>
    <span class="errors">
      <%= answer.errors[:content].join(',') %>
    </span>
  <% end %>
<% end %>

app/views/answers/edit.html.erb
<h1>Update Your Answer Here!</h1>
<%= flash[:error] if flash[:error] %>
<%= form_for [@answer] do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>