config/routes.rb
KnOverFlow::Application.routes.draw do
  resources :questions do
    resources :votes, only: [:create]
    resources :comments, only: [:new, :create]
    resources :answers, only: [:new, :create, :edit, :update, :destroy] 
  end

  resources :answers, only: [:edit, :update, :destroy] do
  	resources :comments, only: [:new, :create]
    resources :votes, only: [:create]
  end

  resources :comments, only: [:edit, :update, :destroy]

  root to: 'questions#index'
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KnOverFlow</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <div class="navbar">
      <ul class="nav navbar-nav">
      <li id='brand'><%= link_to "welcome KnowItAll", root_path %></li>
        <% if current_user %>
          <li id='nav_user'><a> <%= User.find(session[:user_id]).name %></a></li>
          <li><%= link_to "log out", session_path(current_user), {method: :delete} %></li>
          <li><%= link_to "ask a question", new_question_path %></li>
        <% else %>
          <li><%= link_to "sign up", new_user_path %>
          <li><%= link_to "sign in", new_session_path %>
        <% end %>
      </ul>
    </div>
    <%= yield %>
  </body>
</html>